# Generated by Django 3.0.8 on 2020-07-26 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='ordered',
        ),
        migrations.AddField(
            model_name='register',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='orderItems',
        ),
        migrations.DeleteModel(
            name='shipping',
        ),
    ]
