# Generated by Django 3.0.8 on 2020-07-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200726_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
