# Generated by Django 3.0.8 on 2020-07-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_customer_order_orderitem_shipping_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='complete',
        ),
    ]
